name: Build and Push

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-n-push:
    runs-on: ubuntu-22.04
    name: build (tags or manual)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Tag
        id: tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api/build/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rinha-backend-q1-2024:${{ steps.tag.outputs.tag }},${{ secrets.DOCKERHUB_USERNAME }}/rinha-backend-q1-2024:latest

    outputs:
      image: :${{ steps.release.outputs.version }}
      tag: ${{ steps.tag.outputs.tag }}